### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by shreyasbharath** [cmcqueen/lzs-compression#1]
Hi Craig,

Can you please add an appropriate license to your library? This will let others like me know whether or not we can use your library in our code.

May I add that a permissive license would be much appreciated!

Thanks!

**Comment by cmcqueen** [comment]
I've added the MIT license to the code. That's the license I normally use for code I've written and shared with the public.

**Comment by shreyasbharath** [comment]
Awesome, thanks!
