### ISSUE TITLE
Support for incremental compression

### ISSUE THREAD

**Issue by shreyasbharath** [cmcqueen/lzs-compression#2]
Hi Craig,

I noticed that the library exposes APIs for "incremental" compression but does not actually implement them.

It would be great if it was implemented.

Thanks!

**Comment by cmcqueen** [comment]
Do you mean the C library or the Python code?

I'm guessing you're referring to the C function `lzs_compress_incremental()` et al.

**Comment by shreyasbharath** [comment]
Yes correct, the C API.

**Comment by cmcqueen** [comment]
I'm happy to implement this in-principle. But I need to find the time in life to do it. At this point, I'm not sure when I might be able to, sorry to say.

**Comment by shreyasbharath** [comment]
I completely understand.

It's just something that would be a nice to have.

**Comment by cmcqueen** [comment]
I've added an implementation of `lzs_compress_incremental()` et al. It works on one test file; I haven't done more thorough testing yet.

**Comment by shreyasbharath** [comment]
That's great! Looking forward to using it :)

**Comment by cmcqueen** [comment]
I'm satisfied with the initial implementation. Other issues cover additional follow-up work such as unit tests, hash table.
